"""The pure domain: no IO, no framework imports, no randomness (enforced by import-linter).

Everything here is data plus total functions over it. Persistence, adapters, and the API are
built on top; nothing here knows they exist.
"""

from orchestrator.domain.capabilities import ProviderCapabilities
from orchestrator.domain.commands import (
    Attempt,
    AttemptOutcome,
    CancelPhase,
    Command,
    CommandKind,
    ConfirmIntent,
    CreateIntent,
    Disposition,
    DispositionBasis,
    InvariantError,
    ProviderRequest,
    SideEffect,
    anchor,
    bind,
    dispatch_allowed,
    exclude_all_possible,
    exclude_attempt,
    note_lookup,
    record_attempt,
    settle,
)
from orchestrator.domain.ids import (
    AttemptId,
    BookingId,
    ClientId,
    CommandId,
    ProviderBookingRef,
    ProviderCode,
)
from orchestrator.domain.money import Money
from orchestrator.domain.refunds import RefundOfferState, RefundOfferStatus, RefundQuote
from orchestrator.domain.replay import Replay, replay_for
from orchestrator.domain.review import (
    Evidence,
    EvidenceKind,
    NotClosable,
    ReviewCase,
    closable_into,
)
from orchestrator.domain.settlement import (
    Abandon,
    Bind,
    Decision,
    Escalate,
    KeepLooking,
    ProviderResult,
    Rejected,
    Reschedule,
    Reservation,
    ReservationState,
    Uncertain,
    decide_abandon,
    decide_create_after_attempt,
    decide_create_after_lookup,
    decide_exhausted,
    decide_late_result,
    identity_mismatch,
    trigger_for,
    trigger_for_escalation,
    trigger_for_reschedule,
)
from orchestrator.domain.states import (
    TERMINAL_STATES,
    BookingState,
    InvalidTransition,
    Trigger,
    transition,
)
from orchestrator.domain.time import NaiveDatetimeError

__all__ = [
    "TERMINAL_STATES",
    "Abandon",
    "Attempt",
    "AttemptId",
    "AttemptOutcome",
    "Bind",
    "BookingId",
    "BookingState",
    "CancelPhase",
    "ClientId",
    "Command",
    "CommandId",
    "CommandKind",
    "ConfirmIntent",
    "CreateIntent",
    "Decision",
    "Disposition",
    "DispositionBasis",
    "Escalate",
    "Evidence",
    "EvidenceKind",
    "InvalidTransition",
    "InvariantError",
    "KeepLooking",
    "Money",
    "NaiveDatetimeError",
    "NotClosable",
    "ProviderBookingRef",
    "ProviderCapabilities",
    "ProviderCode",
    "ProviderRequest",
    "ProviderResult",
    "RefundOfferState",
    "RefundOfferStatus",
    "RefundQuote",
    "Rejected",
    "Replay",
    "Reschedule",
    "Reservation",
    "ReservationState",
    "ReviewCase",
    "SideEffect",
    "Trigger",
    "Uncertain",
    "anchor",
    "bind",
    "closable_into",
    "decide_abandon",
    "decide_create_after_attempt",
    "decide_create_after_lookup",
    "decide_exhausted",
    "decide_late_result",
    "dispatch_allowed",
    "exclude_all_possible",
    "exclude_attempt",
    "identity_mismatch",
    "note_lookup",
    "record_attempt",
    "replay_for",
    "settle",
    "transition",
    "trigger_for",
    "trigger_for_escalation",
    "trigger_for_reschedule",
]
